# -*- coding: utf-8 -*-
"""lab6(AD)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGXVmtPIiDqvxCpDGYE8PWv_v7wUGE_0
"""

##Write a Python program to using NLTK and Spacy
#Convert text to lowercase.
#Remove stopwords using NLTK

import nltk
from nltk.corpus import stopwords
import spacy

nltk.download('stopwords')

def process_text(text):
    text = text.lower()
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    stop_words = set(stopwords.words('english'))
    filtered_words = [token.text for token in doc if token.text not in stop_words]
    return filtered_words

text = "This is an example sentence to demonstrate removing stopwords using NLTK and tokenization using spaCy."
result = process_text(text)

print("Filtered Text:", " ".join(result))

!pip install nltk spacy

!python -m spacy download en_core_web_sm

