# -*- coding: utf-8 -*-
"""lab.5 (AD)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaDumHkKblVEzdTVNiH4cQp6Z2gZrMc4
"""

#1. Write a Python program to calculate the frequency of each word in a given text. Print thewords and their corresponding counts
from collections import Counter

def count_word_frequencies(text):
    text = text.lower()
    for char in '-.,\n':
        text = text.replace(char, ' ')
    words = text.split()
    word_counts = Counter(words)
    return word_counts

text = "Hello world! Hello everyone. This is a sample text, with words: hello, world, sample."
word_frequencies = count_word_frequencies(text)

for word, count in word_frequencies.items():
    print(f"'{word}': {count}")