# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161BUhrpiKwGOn8Elkf0uZyp6TdNrJ46J
"""

my_int = 42
print("original integer:",my_int)

my_list = [1,"hello",3.14,True]
print("Original list:",my_list)

my_list.append("world")
print("list  after appending 'world':",my_list)

my_tuple = (1,'apple', 3.14,False)
print("original Tuple:", my_tuple)

for i in range(1,6):
  print(1)

i=1
while i <=5:
  print(i)

def greet(name):
  """This function takes a name as an argument and prints a  greeting."""
  print(f"Hello function,{name}!")